#!/usr/bin/env python3
"""Generate wheel_duff.h: 64 specialized crossing-cycle cases (k, t) for
cross_flat, with wheel constants baked in as immediates (primesieve-style
Duff's device). Mirrors build_cross_tables() exactly."""

OFFB = [7, 11, 13, 17, 19, 23, 29, 31]
UNITS = [1, 7, 11, 13, 17, 19, 23, 29]

# CV[k][t], CB[k][t], BIT[k][t] identical to build_cross_tables()
CV = [[0] * 8 for _ in range(8)]
CB = [[0] * 8 for _ in range(8)]
BIT = [[0] * 8 for _ in range(8)]
for k in range(8):
    ri = OFFB[k] % 30
    for j in range(8):
        kk = UNITS[j]
        off = (ri * kk) % 30
        dk = (UNITS[j + 1] - UNITS[j]) if j < 7 else (31 - UNITS[7])
        g = (off - 6 + 30) % 30
        cb = (g + ri * dk) // 30
        bit_off = 31 if off == 1 else off
        b = OFFB.index(bit_off)
        CV[k][j] = dk
        CB[k][j] = cb
        BIT[k][j] = (u8 := 0xFF & ~(1 << b))

out = []
out.append("/* generated by tools/gen_wheel_duff.py - do not edit by hand */")
for k in range(8):
    for t0 in range(8):
        tj = [(t0 + m) & 7 for m in range(8)]
        # store j uses BIT[k][t_j]; offset of store j = sum of steps t0..t0+j-1
        cum_cv, cum_cb = 0, 0
        offs = []
        for m in range(8):  # offs[0] = 0 (the base multiple)
            offs.append((cum_cv, cum_cb))
            cum_cv += CV[k][tj[m]]
            cum_cb += CB[k][tj[m]]
        stride = (cum_cv, cum_cb)
        msk = [BIT[k][t] for t in tj]
        case = k * 8 + t0
        L = []
        L.append(
            f"      case {case}: {{   /* k={k} (p mod 30 = {OFFB[k] % 30}), enter at t={t0} */"
        )
        L.append(f"        u32 o1 = {offs[1][1]}u + {offs[1][0]}u * sp;")
        for j in range(2, 8):
            # offs[j] is the ABSOLUTE cumulative offset of store j (o0 = 0)
            L.append(f"        u32 o{j} = {offs[j][1]}u + {offs[j][0]}u * sp;")
        L.append(f"        u32 strd = {stride[1]}u + {stride[0]}u * sp;")
        st = "        while (i + (u64)o7 < B) {"
        L.append(st)
        L.append(f"          s[i] &= 0x{msk[0]:02X}u;")
        for j in range(1, 8):
            L.append(f"          s[i + o{j}] &= 0x{msk[j]:02X}u;")
        L.append("          i += strd;")
        L.append("          if (i >= B) { i -= B; goto done; }")
        L.append("        }")
        L.append("        break; }")
        out.extend(L)
open("wheel_duff.h", "w").write("\n".join(out) + "\n")
print(f"wheel_duff.h written: {len(out)} lines")
